---
- name: Git pull master
  git:
    repo: "{{ git_url }}"
    dest: "{{ git_root }}"
    update: yes
    version: master
    accept_hostkey: yes
    force: yes

- name: Install dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - aptitude
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add an apt signing key for docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for docker
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install pip
  become: yes
  apt:
    name: python-pip
    state: present

- name: Install docker-py package
  become: yes
  pip:
    name: docker-py

- name: Start docker service
  service:
    name: docker
    state: started

- name: Docker build image
  become: yes
  docker_image:
    name: phrasegen
    build:
      path: "{{ git_root }}"
      pull: yes
    tag: latest
    force_source: yes
    source: build

- name: Allow ubuntu user to access the docker engine
  become: yes
  command: usermod -a -G docker ubuntu
